name: VinylReleases → ntfy

on:
  schedule:
    - cron: "*/11 13-23 * * *"   # every 11 minutes, 6am–6pm PT (approx, accounts for UTC offset)
  workflow_dispatch:             # lets you run it manually

permissions:
  contents: read

env:
  FEED_URL: https://www.reddit.com/r/VinylReleases/new/.rss
  NTFY_TOPIC: vinyl_alerts
  WINDOW_MINUTES: "12"           # look back slightly more than 11m

jobs:
  send_alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install feedparser requests

      - name: Poll RSS and post to ntfy
        run: |
          python3 << 'EOF'
          import os, requests, feedparser, datetime
          FEED_URL = os.environ["FEED_URL"]
          TOPIC = os.environ["NTFY_TOPIC"]
          WINDOW_MINUTES = int(os.environ["WINDOW_MINUTES"])
          
          feed = feedparser.parse(FEED_URL)
          cutoff = datetime.datetime.utcnow() - datetime.timedelta(minutes=WINDOW_MINUTES)

          for entry in feed.entries:
              if hasattr(entry, "published_parsed"):
                  published = datetime.datetime(*entry.published_parsed[:6])
                  if published > cutoff:
                      msg = f"{entry.title}\n{entry.link}"
                      requests.post(f"https://ntfy.sh/{TOPIC}", data=msg.encode("utf-8"))
          EOF
