name: VinylReleases → ntfy

on:
  schedule:
    # Run every 12 minutes between 6 AM and 6 PM Pacific (13–01 UTC)
    - cron: "*/12 13-23 * * *"
    - cron: "*/12 0-1 * * *"
  workflow_dispatch:    # lets you run it manually

permissions:
  contents: read

env:
  FEED_URL: https://www.reddit.com/r/VinylReleases/new/.rss
  NTFY_TOPIC: vinyl_alerts
  WINDOW_MINUTES: "13"   # look back slightly more than 12m

jobs:
  send_alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install feedparser requests

      - name: Poll RSS and post to ntfy
        run: |
          import feedparser, requests, os
          from datetime import datetime, timedelta, timezone

          feed_url = os.environ["FEED_URL"]
          topic = os.environ["NTFY_TOPIC"]
          window_minutes = int(os.environ["WINDOW_MINUTES"])

          cutoff = datetime.now(timezone.utc) - timedelta(minutes=window_minutes)

          feed = feedparser.parse(feed_url)

          for entry in feed.entries:
              if hasattr(entry, "published_parsed"):
                  published = datetime(*entry.published_parsed[:6], tzinfo=timezone.utc)
                  if published > cutoff:
                      msg = f"{entry.title}\n{entry.link}"
                      requests.post(f"https://ntfy.sh/{topic}", data=msg.encode("utf-8"))
        shell: python3 {0}
